/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GameResult = IDL.Record({
  'oWins' : IDL.Nat,
  'xWins' : IDL.Nat,
  'draws' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getScores' : IDL.Func([], [GameResult], ['query']),
  'recordGameResult' : IDL.Func([IDL.Text], [], []),
  'resetScores' : IDL.Func([], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GameResult = IDL.Record({
    'oWins' : IDL.Nat,
    'xWins' : IDL.Nat,
    'draws' : IDL.Nat,
  });
  
  return IDL.Service({
    'getScores' : IDL.Func([], [GameResult], ['query']),
    'recordGameResult' : IDL.Func([IDL.Text], [], []),
    'resetScores' : IDL.Func([], [], []),
  });
};

export const init = ({ IDL }) => { return []; };